fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]

      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run coverage run -m pytest
        types: [python]
        always_run: true
        pass_filenames: false

      - id: coverage
        name: coverage
        stages: [push]
        language: system
        entry: pipenv run coverage report
        types: [python]
        always_run: true
        pass_filenames: false
